# Generated by Django 5.2 on 2025-04-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_address_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.CharField(blank=True, choices=[('entry_level', 'Entry-Level'), ('mid_level', 'Mid-Level'), ('expert_level', 'Expert-Level')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
